-- Create the customers table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT UNIQUE,
    email TEXT,
    gst_number TEXT UNIQUE,
    address TEXT,
    user_id UUID REFERENCES auth.users(id),
    UNIQUE(user_id, name) -- Name unique per user
);

-- Enable Row Level Security (RLS)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- Create policies so users can only see/edit their own customers
CREATE POLICY "Users can view their own customers" 
ON customers FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own customers" 
ON customers FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own customers" 
ON customers FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own customers" 
ON customers FOR DELETE 
USING (auth.uid() = user_id);
